import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddStarships1704838503758 implements MigrationInterface {
  name = 'AddStarships1704838503758';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "species_people" DROP CONSTRAINT "FK_3fcb52d51b8b93c9707ac164d8a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_people" DROP CONSTRAINT "FK_8019a9b0a4e75b66f02bc76a7c1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_films" DROP CONSTRAINT "FK_f9d0038e205e511024d88b4c441"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_films" DROP CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" DROP CONSTRAINT "FK_1b9e498a7b6714398614766c245"`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" DROP CONSTRAINT "FK_d7f4d68dc596fce125db571c771"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_films" DROP CONSTRAINT "FK_80755b97f28bfae4f163d389609"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_films" DROP CONSTRAINT "FK_c39d2aecfd9c301a9cd5bc3aef7"`,
    );
    await queryRunner.query(
      `CREATE TABLE "starships" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "model" character varying NOT NULL, "manufacturer" character varying NOT NULL, "cost_in_credits" character varying NOT NULL, "length" character varying NOT NULL, "max_atmosphering_speed" character varying NOT NULL, "crew" character varying NOT NULL, "passengers" character varying NOT NULL, "cargo_capacity" character varying NOT NULL, "consumables" character varying NOT NULL, "hyperdrive_rating" character varying NOT NULL, "MGLT" character varying NOT NULL, "starship_class" character varying NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "edited" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_41580e76da7903fb3827a3510eb" UNIQUE ("name"), CONSTRAINT "PK_10c86d0ac9be05d3f986287a092" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "starships_people" ("starshipsId" integer NOT NULL, "peopleId" integer NOT NULL, CONSTRAINT "PK_59bd5a10298d34b1a7f51558bb2" PRIMARY KEY ("starshipsId", "peopleId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_917a4f5268f5c608fc22bb5f11" ON "starships_people" ("starshipsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_26d0aa1855752c3b47b6703a69" ON "starships_people" ("peopleId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "starships_films" ("starshipsId" integer NOT NULL, "filmsId" integer NOT NULL, CONSTRAINT "PK_4623e42141b71c2f0842a54b104" PRIMARY KEY ("starshipsId", "filmsId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_93b7fe60939bacb7164b891808" ON "starships_films" ("starshipsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_eec7368a97fd52db1abdce959c" ON "starships_films" ("filmsId") `,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" ADD CONSTRAINT "FK_1b9e498a7b6714398614766c245" FOREIGN KEY ("planetsId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" ADD CONSTRAINT "FK_d7f4d68dc596fce125db571c771" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_people" ADD CONSTRAINT "FK_3fcb52d51b8b93c9707ac164d8a" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_people" ADD CONSTRAINT "FK_8019a9b0a4e75b66f02bc76a7c1" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_films" ADD CONSTRAINT "FK_80755b97f28bfae4f163d389609" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_films" ADD CONSTRAINT "FK_c39d2aecfd9c301a9cd5bc3aef7" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_people" ADD CONSTRAINT "FK_917a4f5268f5c608fc22bb5f110" FOREIGN KEY ("starshipsId") REFERENCES "starships"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_people" ADD CONSTRAINT "FK_26d0aa1855752c3b47b6703a69e" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_films" ADD CONSTRAINT "FK_93b7fe60939bacb7164b891808a" FOREIGN KEY ("starshipsId") REFERENCES "starships"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_films" ADD CONSTRAINT "FK_eec7368a97fd52db1abdce959cb" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_films" ADD CONSTRAINT "FK_f9d0038e205e511024d88b4c441" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_films" ADD CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "people_films" DROP CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_films" DROP CONSTRAINT "FK_f9d0038e205e511024d88b4c441"`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_films" DROP CONSTRAINT "FK_eec7368a97fd52db1abdce959cb"`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_films" DROP CONSTRAINT "FK_93b7fe60939bacb7164b891808a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_people" DROP CONSTRAINT "FK_26d0aa1855752c3b47b6703a69e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_people" DROP CONSTRAINT "FK_917a4f5268f5c608fc22bb5f110"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_films" DROP CONSTRAINT "FK_c39d2aecfd9c301a9cd5bc3aef7"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_films" DROP CONSTRAINT "FK_80755b97f28bfae4f163d389609"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_people" DROP CONSTRAINT "FK_8019a9b0a4e75b66f02bc76a7c1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_people" DROP CONSTRAINT "FK_3fcb52d51b8b93c9707ac164d8a"`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" DROP CONSTRAINT "FK_d7f4d68dc596fce125db571c771"`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" DROP CONSTRAINT "FK_1b9e498a7b6714398614766c245"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_eec7368a97fd52db1abdce959c"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_93b7fe60939bacb7164b891808"`,
    );
    await queryRunner.query(`DROP TABLE "starships_films"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_26d0aa1855752c3b47b6703a69"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_917a4f5268f5c608fc22bb5f11"`,
    );
    await queryRunner.query(`DROP TABLE "starships_people"`);
    await queryRunner.query(`DROP TABLE "starships"`);
    await queryRunner.query(
      `ALTER TABLE "species_films" ADD CONSTRAINT "FK_c39d2aecfd9c301a9cd5bc3aef7" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_films" ADD CONSTRAINT "FK_80755b97f28bfae4f163d389609" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" ADD CONSTRAINT "FK_d7f4d68dc596fce125db571c771" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_films" ADD CONSTRAINT "FK_1b9e498a7b6714398614766c245" FOREIGN KEY ("planetsId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_films" ADD CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_films" ADD CONSTRAINT "FK_f9d0038e205e511024d88b4c441" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_people" ADD CONSTRAINT "FK_8019a9b0a4e75b66f02bc76a7c1" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_people" ADD CONSTRAINT "FK_3fcb52d51b8b93c9707ac164d8a" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  }
}
