import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSpecies1704837555524 implements MigrationInterface {
    name = 'AddSpecies1704837555524'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "people_films" DROP CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f"`);
        await queryRunner.query(`ALTER TABLE "people_films" DROP CONSTRAINT "FK_f9d0038e205e511024d88b4c441"`);
        await queryRunner.query(`ALTER TABLE "planets_films" DROP CONSTRAINT "FK_d7f4d68dc596fce125db571c771"`);
        await queryRunner.query(`ALTER TABLE "planets_films" DROP CONSTRAINT "FK_1b9e498a7b6714398614766c245"`);
        await queryRunner.query(`CREATE TABLE "species" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" character varying NOT NULL, "classification" character varying NOT NULL, "designation" character varying NOT NULL, "average_height" character varying NOT NULL, "skin_colors" character varying NOT NULL, "hair_colors" character varying NOT NULL, "eye_colors" character varying NOT NULL, "average_lifespan" integer NOT NULL, "language" character varying NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "edited" TIMESTAMP NOT NULL DEFAULT now(), "homeworldId" integer, CONSTRAINT "PK_ae6a87f2423ba6c25dc43c32770" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "species_people" ("speciesId" integer NOT NULL, "peopleId" integer NOT NULL, CONSTRAINT "PK_3746d2b49376d40e2b65ca845cd" PRIMARY KEY ("speciesId", "peopleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3fcb52d51b8b93c9707ac164d8" ON "species_people" ("speciesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8019a9b0a4e75b66f02bc76a7c" ON "species_people" ("peopleId") `);
        await queryRunner.query(`CREATE TABLE "species_films" ("speciesId" integer NOT NULL, "filmsId" integer NOT NULL, CONSTRAINT "PK_61891ef4f6e91b846b60d7f7be0" PRIMARY KEY ("speciesId", "filmsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80755b97f28bfae4f163d38960" ON "species_films" ("speciesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c39d2aecfd9c301a9cd5bc3aef" ON "species_films" ("filmsId") `);
        await queryRunner.query(`ALTER TABLE "species" ADD CONSTRAINT "FK_3427f7c92316561d7131c296bc6" FOREIGN KEY ("homeworldId") REFERENCES "planets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "planets_films" ADD CONSTRAINT "FK_1b9e498a7b6714398614766c245" FOREIGN KEY ("planetsId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planets_films" ADD CONSTRAINT "FK_d7f4d68dc596fce125db571c771" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "species_people" ADD CONSTRAINT "FK_3fcb52d51b8b93c9707ac164d8a" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "species_people" ADD CONSTRAINT "FK_8019a9b0a4e75b66f02bc76a7c1" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "species_films" ADD CONSTRAINT "FK_80755b97f28bfae4f163d389609" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "species_films" ADD CONSTRAINT "FK_c39d2aecfd9c301a9cd5bc3aef7" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people_films" ADD CONSTRAINT "FK_f9d0038e205e511024d88b4c441" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "people_films" ADD CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "people_films" DROP CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f"`);
        await queryRunner.query(`ALTER TABLE "people_films" DROP CONSTRAINT "FK_f9d0038e205e511024d88b4c441"`);
        await queryRunner.query(`ALTER TABLE "species_films" DROP CONSTRAINT "FK_c39d2aecfd9c301a9cd5bc3aef7"`);
        await queryRunner.query(`ALTER TABLE "species_films" DROP CONSTRAINT "FK_80755b97f28bfae4f163d389609"`);
        await queryRunner.query(`ALTER TABLE "species_people" DROP CONSTRAINT "FK_8019a9b0a4e75b66f02bc76a7c1"`);
        await queryRunner.query(`ALTER TABLE "species_people" DROP CONSTRAINT "FK_3fcb52d51b8b93c9707ac164d8a"`);
        await queryRunner.query(`ALTER TABLE "planets_films" DROP CONSTRAINT "FK_d7f4d68dc596fce125db571c771"`);
        await queryRunner.query(`ALTER TABLE "planets_films" DROP CONSTRAINT "FK_1b9e498a7b6714398614766c245"`);
        await queryRunner.query(`ALTER TABLE "species" DROP CONSTRAINT "FK_3427f7c92316561d7131c296bc6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c39d2aecfd9c301a9cd5bc3aef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80755b97f28bfae4f163d38960"`);
        await queryRunner.query(`DROP TABLE "species_films"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8019a9b0a4e75b66f02bc76a7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fcb52d51b8b93c9707ac164d8"`);
        await queryRunner.query(`DROP TABLE "species_people"`);
        await queryRunner.query(`DROP TABLE "species"`);
        await queryRunner.query(`ALTER TABLE "planets_films" ADD CONSTRAINT "FK_1b9e498a7b6714398614766c245" FOREIGN KEY ("planetsId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "planets_films" ADD CONSTRAINT "FK_d7f4d68dc596fce125db571c771" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people_films" ADD CONSTRAINT "FK_f9d0038e205e511024d88b4c441" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "people_films" ADD CONSTRAINT "FK_a6ae8e23d835bdbc6b9fe43823f" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
