import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddOtherEntitiesWithRelations1720995698423
  implements MigrationInterface
{
  name = 'AddOtherEntitiesWithRelations1720995698423';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "image" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "link" character varying NOT NULL, CONSTRAINT "PK_d6db1ab4ee9ad9dbe86c64e4cc3" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "planets" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "edited" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "rotation_period" character varying NOT NULL, "orbital_period" character varying NOT NULL, "diameter" character varying NOT NULL, "climate" character varying NOT NULL, "gravity" character varying NOT NULL, "terrain" character varying NOT NULL, "surface_water" character varying NOT NULL, "population" character varying NOT NULL, CONSTRAINT "PK_d5fbc2513a6d4909fe31938b0fd" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "species" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "edited" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "classification" character varying NOT NULL, "designation" character varying NOT NULL, "average_height" character varying NOT NULL, "skin_colors" character varying NOT NULL, "hair_colors" character varying NOT NULL, "eye_colors" character varying NOT NULL, "average_lifespan" character varying NOT NULL, "language" character varying NOT NULL, "homeworldId" integer, CONSTRAINT "UQ_1adf701cac3b2c0f8bacb54774b" UNIQUE ("name"), CONSTRAINT "PK_ae6a87f2423ba6c25dc43c32770" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "starships" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "edited" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "model" character varying NOT NULL, "manufacturer" character varying NOT NULL, "cost_in_credits" character varying NOT NULL, "length" character varying NOT NULL, "max_atmosphering_speed" character varying NOT NULL, "crew" character varying NOT NULL, "passengers" character varying NOT NULL, "cargo_capacity" character varying NOT NULL, "consumables" character varying NOT NULL, "hyperdrive_rating" character varying NOT NULL, "MGLT" character varying NOT NULL, "starship_class" character varying NOT NULL, CONSTRAINT "UQ_41580e76da7903fb3827a3510eb" UNIQUE ("name"), CONSTRAINT "PK_10c86d0ac9be05d3f986287a092" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "vehicles" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created" TIMESTAMP NOT NULL DEFAULT now(), "edited" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "model" character varying NOT NULL, "manufacturer" character varying NOT NULL, "cost_in_credits" character varying NOT NULL, "length" character varying NOT NULL, "max_atmosphering_speed" character varying NOT NULL, "crew" character varying NOT NULL, "passengers" character varying NOT NULL, "cargo_capacity" character varying NOT NULL, "consumables" character varying NOT NULL, "vehicle_class" character varying NOT NULL, CONSTRAINT "UQ_aa397b791341ed3615397050d4b" UNIQUE ("name"), CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "planets_images_image" ("planetsId" integer NOT NULL, "imageId" integer NOT NULL, CONSTRAINT "PK_9e7dcd3961e451b9a69cd476358" PRIMARY KEY ("planetsId", "imageId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_603003d4f58748f30a967a4a03" ON "planets_images_image" ("planetsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_a51529a5edcdbb2f94d1b96a2c" ON "planets_images_image" ("imageId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "species_images_image" ("speciesId" integer NOT NULL, "imageId" integer NOT NULL, CONSTRAINT "PK_f390d2b7aa845c783fca946ed80" PRIMARY KEY ("speciesId", "imageId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_1454c6095b3e6daf56454f1de3" ON "species_images_image" ("speciesId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_ce479ab78ecf35b916fb8552ae" ON "species_images_image" ("imageId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "starships_images_image" ("starshipsId" integer NOT NULL, "imageId" integer NOT NULL, CONSTRAINT "PK_315c25148c022c21a632179c0e4" PRIMARY KEY ("starshipsId", "imageId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_0c1f3819f2bbc863d9fef1a7ba" ON "starships_images_image" ("starshipsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_9f0806e270beaa53e8ae0ce2e7" ON "starships_images_image" ("imageId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "vehicles_images_image" ("vehiclesId" integer NOT NULL, "imageId" integer NOT NULL, CONSTRAINT "PK_21aba587571a0ccb8034e6bce6f" PRIMARY KEY ("vehiclesId", "imageId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_4b6e250d32cb80260a2d26d383" ON "vehicles_images_image" ("vehiclesId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_32a4fb7e75ba3661e4072442a6" ON "vehicles_images_image" ("imageId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "people_species_species" ("peopleId" integer NOT NULL, "speciesId" integer NOT NULL, CONSTRAINT "PK_a9367442a2f340b0f020cd592b0" PRIMARY KEY ("peopleId", "speciesId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_d6d545e4740ee652e6f79e9ffd" ON "people_species_species" ("peopleId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_9232984d4ee14342ad97f44382" ON "people_species_species" ("speciesId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "people_vehicles_vehicles" ("peopleId" integer NOT NULL, "vehiclesId" integer NOT NULL, CONSTRAINT "PK_69addbf10105a9276f277fae411" PRIMARY KEY ("peopleId", "vehiclesId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_a7b8cbe95c602d58ade9845ce6" ON "people_vehicles_vehicles" ("peopleId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_f872d6f9465604601135f41970" ON "people_vehicles_vehicles" ("vehiclesId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "people_starships_starships" ("peopleId" integer NOT NULL, "starshipsId" integer NOT NULL, CONSTRAINT "PK_fd849a9c3ab64a62004d47402bb" PRIMARY KEY ("peopleId", "starshipsId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_78e90ed25ace2390fa2c7a4d50" ON "people_starships_starships" ("peopleId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_0a5517fc734c462fc3a0d32eb9" ON "people_starships_starships" ("starshipsId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "people_images_image" ("peopleId" integer NOT NULL, "imageId" integer NOT NULL, CONSTRAINT "PK_c8921cbeb79d0188fb7f83473b1" PRIMARY KEY ("peopleId", "imageId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_a9abbede98b7b3ef382f4734f5" ON "people_images_image" ("peopleId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_0de7f83974d96f530e3ee2b61c" ON "people_images_image" ("imageId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "films_characters_people" ("filmsId" integer NOT NULL, "peopleId" integer NOT NULL, CONSTRAINT "PK_13beaa853a90e105eb6b704530a" PRIMARY KEY ("filmsId", "peopleId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_ca23a410c5afe74468664fc093" ON "films_characters_people" ("filmsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_8f835d0e20d5e12a9d1eff662f" ON "films_characters_people" ("peopleId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "films_planets_planets" ("filmsId" integer NOT NULL, "planetsId" integer NOT NULL, CONSTRAINT "PK_a5a8f53f9e8b8e7a870dc8a6160" PRIMARY KEY ("filmsId", "planetsId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_59f34f486757575a016c375061" ON "films_planets_planets" ("filmsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_956e9e10fd96ed618538bb2b96" ON "films_planets_planets" ("planetsId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "films_starships_starships" ("filmsId" integer NOT NULL, "starshipsId" integer NOT NULL, CONSTRAINT "PK_f7c410e6e8b54adc51f99e0f386" PRIMARY KEY ("filmsId", "starshipsId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_3965a3d69c030eca6799a06d9d" ON "films_starships_starships" ("filmsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_e79353f238988153784b207757" ON "films_starships_starships" ("starshipsId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "films_vehicles_vehicles" ("filmsId" integer NOT NULL, "vehiclesId" integer NOT NULL, CONSTRAINT "PK_78db1bf247c879baf20c6c9c2af" PRIMARY KEY ("filmsId", "vehiclesId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_21c53d0d80b975c872a4ca4ada" ON "films_vehicles_vehicles" ("filmsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_a623eaa88213329f69118cdea5" ON "films_vehicles_vehicles" ("vehiclesId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "films_species_species" ("filmsId" integer NOT NULL, "speciesId" integer NOT NULL, CONSTRAINT "PK_b16e4a6a250dfe1872c561203d0" PRIMARY KEY ("filmsId", "speciesId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_be1d816ce6bdc4677080067eb4" ON "films_species_species" ("filmsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_6042e3f9819bb64e4264509f73" ON "films_species_species" ("speciesId") `,
    );
    await queryRunner.query(
      `CREATE TABLE "films_images_image" ("filmsId" integer NOT NULL, "imageId" integer NOT NULL, CONSTRAINT "PK_e3c97f1cd9dafd0e9c75d28c5c8" PRIMARY KEY ("filmsId", "imageId"))`,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_655f6983fce7b5aa099c2032f5" ON "films_images_image" ("filmsId") `,
    );
    await queryRunner.query(
      `CREATE INDEX "IDX_76c2518ee72f4a7757e7813db8" ON "films_images_image" ("imageId") `,
    );
    await queryRunner.query(`ALTER TABLE "people" ADD "homeworldId" integer`);
    await queryRunner.query(
      `ALTER TABLE "people" ALTER COLUMN "birth_year" DROP NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "species" ADD CONSTRAINT "FK_3427f7c92316561d7131c296bc6" FOREIGN KEY ("homeworldId") REFERENCES "planets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "people" ADD CONSTRAINT "FK_8f79bb098a482fa585da15ef3a6" FOREIGN KEY ("homeworldId") REFERENCES "planets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_images_image" ADD CONSTRAINT "FK_603003d4f58748f30a967a4a037" FOREIGN KEY ("planetsId") REFERENCES "planets"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_images_image" ADD CONSTRAINT "FK_a51529a5edcdbb2f94d1b96a2cb" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_images_image" ADD CONSTRAINT "FK_1454c6095b3e6daf56454f1de39" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_images_image" ADD CONSTRAINT "FK_ce479ab78ecf35b916fb8552ae4" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_images_image" ADD CONSTRAINT "FK_0c1f3819f2bbc863d9fef1a7ba1" FOREIGN KEY ("starshipsId") REFERENCES "starships"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_images_image" ADD CONSTRAINT "FK_9f0806e270beaa53e8ae0ce2e77" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "vehicles_images_image" ADD CONSTRAINT "FK_4b6e250d32cb80260a2d26d3837" FOREIGN KEY ("vehiclesId") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "vehicles_images_image" ADD CONSTRAINT "FK_32a4fb7e75ba3661e4072442a69" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_species_species" ADD CONSTRAINT "FK_d6d545e4740ee652e6f79e9ffd5" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_species_species" ADD CONSTRAINT "FK_9232984d4ee14342ad97f443824" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_vehicles_vehicles" ADD CONSTRAINT "FK_a7b8cbe95c602d58ade9845ce63" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_vehicles_vehicles" ADD CONSTRAINT "FK_f872d6f9465604601135f419704" FOREIGN KEY ("vehiclesId") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_starships_starships" ADD CONSTRAINT "FK_78e90ed25ace2390fa2c7a4d50c" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_starships_starships" ADD CONSTRAINT "FK_0a5517fc734c462fc3a0d32eb99" FOREIGN KEY ("starshipsId") REFERENCES "starships"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_images_image" ADD CONSTRAINT "FK_a9abbede98b7b3ef382f4734f57" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_images_image" ADD CONSTRAINT "FK_0de7f83974d96f530e3ee2b61c2" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_characters_people" ADD CONSTRAINT "FK_ca23a410c5afe74468664fc0936" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_characters_people" ADD CONSTRAINT "FK_8f835d0e20d5e12a9d1eff662fd" FOREIGN KEY ("peopleId") REFERENCES "people"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_planets_planets" ADD CONSTRAINT "FK_59f34f486757575a016c3750616" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_planets_planets" ADD CONSTRAINT "FK_956e9e10fd96ed618538bb2b96c" FOREIGN KEY ("planetsId") REFERENCES "planets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_starships_starships" ADD CONSTRAINT "FK_3965a3d69c030eca6799a06d9d7" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_starships_starships" ADD CONSTRAINT "FK_e79353f238988153784b207757c" FOREIGN KEY ("starshipsId") REFERENCES "starships"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_vehicles_vehicles" ADD CONSTRAINT "FK_21c53d0d80b975c872a4ca4ada3" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_vehicles_vehicles" ADD CONSTRAINT "FK_a623eaa88213329f69118cdea5d" FOREIGN KEY ("vehiclesId") REFERENCES "vehicles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_species_species" ADD CONSTRAINT "FK_be1d816ce6bdc4677080067eb4b" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_species_species" ADD CONSTRAINT "FK_6042e3f9819bb64e4264509f73e" FOREIGN KEY ("speciesId") REFERENCES "species"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_images_image" ADD CONSTRAINT "FK_655f6983fce7b5aa099c2032f56" FOREIGN KEY ("filmsId") REFERENCES "films"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_images_image" ADD CONSTRAINT "FK_76c2518ee72f4a7757e7813db84" FOREIGN KEY ("imageId") REFERENCES "image"("id") ON DELETE CASCADE ON UPDATE CASCADE`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "films_images_image" DROP CONSTRAINT "FK_76c2518ee72f4a7757e7813db84"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_images_image" DROP CONSTRAINT "FK_655f6983fce7b5aa099c2032f56"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_species_species" DROP CONSTRAINT "FK_6042e3f9819bb64e4264509f73e"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_species_species" DROP CONSTRAINT "FK_be1d816ce6bdc4677080067eb4b"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_vehicles_vehicles" DROP CONSTRAINT "FK_a623eaa88213329f69118cdea5d"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_vehicles_vehicles" DROP CONSTRAINT "FK_21c53d0d80b975c872a4ca4ada3"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_starships_starships" DROP CONSTRAINT "FK_e79353f238988153784b207757c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_starships_starships" DROP CONSTRAINT "FK_3965a3d69c030eca6799a06d9d7"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_planets_planets" DROP CONSTRAINT "FK_956e9e10fd96ed618538bb2b96c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_planets_planets" DROP CONSTRAINT "FK_59f34f486757575a016c3750616"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_characters_people" DROP CONSTRAINT "FK_8f835d0e20d5e12a9d1eff662fd"`,
    );
    await queryRunner.query(
      `ALTER TABLE "films_characters_people" DROP CONSTRAINT "FK_ca23a410c5afe74468664fc0936"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_images_image" DROP CONSTRAINT "FK_0de7f83974d96f530e3ee2b61c2"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_images_image" DROP CONSTRAINT "FK_a9abbede98b7b3ef382f4734f57"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_starships_starships" DROP CONSTRAINT "FK_0a5517fc734c462fc3a0d32eb99"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_starships_starships" DROP CONSTRAINT "FK_78e90ed25ace2390fa2c7a4d50c"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_vehicles_vehicles" DROP CONSTRAINT "FK_f872d6f9465604601135f419704"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_vehicles_vehicles" DROP CONSTRAINT "FK_a7b8cbe95c602d58ade9845ce63"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_species_species" DROP CONSTRAINT "FK_9232984d4ee14342ad97f443824"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people_species_species" DROP CONSTRAINT "FK_d6d545e4740ee652e6f79e9ffd5"`,
    );
    await queryRunner.query(
      `ALTER TABLE "vehicles_images_image" DROP CONSTRAINT "FK_32a4fb7e75ba3661e4072442a69"`,
    );
    await queryRunner.query(
      `ALTER TABLE "vehicles_images_image" DROP CONSTRAINT "FK_4b6e250d32cb80260a2d26d3837"`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_images_image" DROP CONSTRAINT "FK_9f0806e270beaa53e8ae0ce2e77"`,
    );
    await queryRunner.query(
      `ALTER TABLE "starships_images_image" DROP CONSTRAINT "FK_0c1f3819f2bbc863d9fef1a7ba1"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_images_image" DROP CONSTRAINT "FK_ce479ab78ecf35b916fb8552ae4"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species_images_image" DROP CONSTRAINT "FK_1454c6095b3e6daf56454f1de39"`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_images_image" DROP CONSTRAINT "FK_a51529a5edcdbb2f94d1b96a2cb"`,
    );
    await queryRunner.query(
      `ALTER TABLE "planets_images_image" DROP CONSTRAINT "FK_603003d4f58748f30a967a4a037"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people" DROP CONSTRAINT "FK_8f79bb098a482fa585da15ef3a6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "species" DROP CONSTRAINT "FK_3427f7c92316561d7131c296bc6"`,
    );
    await queryRunner.query(
      `ALTER TABLE "people" ALTER COLUMN "birth_year" SET NOT NULL`,
    );
    await queryRunner.query(`ALTER TABLE "people" DROP COLUMN "homeworldId"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_76c2518ee72f4a7757e7813db8"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_655f6983fce7b5aa099c2032f5"`,
    );
    await queryRunner.query(`DROP TABLE "films_images_image"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_6042e3f9819bb64e4264509f73"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_be1d816ce6bdc4677080067eb4"`,
    );
    await queryRunner.query(`DROP TABLE "films_species_species"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_a623eaa88213329f69118cdea5"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_21c53d0d80b975c872a4ca4ada"`,
    );
    await queryRunner.query(`DROP TABLE "films_vehicles_vehicles"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_e79353f238988153784b207757"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_3965a3d69c030eca6799a06d9d"`,
    );
    await queryRunner.query(`DROP TABLE "films_starships_starships"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_956e9e10fd96ed618538bb2b96"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_59f34f486757575a016c375061"`,
    );
    await queryRunner.query(`DROP TABLE "films_planets_planets"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_8f835d0e20d5e12a9d1eff662f"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_ca23a410c5afe74468664fc093"`,
    );
    await queryRunner.query(`DROP TABLE "films_characters_people"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_0de7f83974d96f530e3ee2b61c"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_a9abbede98b7b3ef382f4734f5"`,
    );
    await queryRunner.query(`DROP TABLE "people_images_image"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_0a5517fc734c462fc3a0d32eb9"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_78e90ed25ace2390fa2c7a4d50"`,
    );
    await queryRunner.query(`DROP TABLE "people_starships_starships"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_f872d6f9465604601135f41970"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_a7b8cbe95c602d58ade9845ce6"`,
    );
    await queryRunner.query(`DROP TABLE "people_vehicles_vehicles"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_9232984d4ee14342ad97f44382"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_d6d545e4740ee652e6f79e9ffd"`,
    );
    await queryRunner.query(`DROP TABLE "people_species_species"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_32a4fb7e75ba3661e4072442a6"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_4b6e250d32cb80260a2d26d383"`,
    );
    await queryRunner.query(`DROP TABLE "vehicles_images_image"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_9f0806e270beaa53e8ae0ce2e7"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_0c1f3819f2bbc863d9fef1a7ba"`,
    );
    await queryRunner.query(`DROP TABLE "starships_images_image"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_ce479ab78ecf35b916fb8552ae"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_1454c6095b3e6daf56454f1de3"`,
    );
    await queryRunner.query(`DROP TABLE "species_images_image"`);
    await queryRunner.query(
      `DROP INDEX "public"."IDX_a51529a5edcdbb2f94d1b96a2c"`,
    );
    await queryRunner.query(
      `DROP INDEX "public"."IDX_603003d4f58748f30a967a4a03"`,
    );
    await queryRunner.query(`DROP TABLE "planets_images_image"`);
    await queryRunner.query(`DROP TABLE "vehicles"`);
    await queryRunner.query(`DROP TABLE "starships"`);
    await queryRunner.query(`DROP TABLE "species"`);
    await queryRunner.query(`DROP TABLE "planets"`);
    await queryRunner.query(`DROP TABLE "image"`);
  }
}
