version: '3.8'
services:
  # NestJS Application
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      # --- Add these environment variables ---
      - DB_HOST=db
      - DB_PORT=5432  # <-- The internal port of the postgres container
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=swapi
      - PORT=3000

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    environment:
      # --- These must match the variables above ---
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swapi
    ports:
      # Expose port 5433 on your local machine and forward to 5432 in the container
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Add a healthcheck to ensure the app waits until the DB is ready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: