version: '3.8'
services:
  # NestJS Application
  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy # Use the healthcheck result
    # The 'env_file' property tells Compose to load variables
    # from the specified file directly into the container.
    env_file:
      - .env

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    # You can also use env_file here for consistency
    env_file:
      - .env
    ports:
      # Map the host port to the container's internal port
      - '${HOST_DB_PORT}:${DB_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: