# render.yaml
services:
  # The NestJS Application
  - type: web
    name: swapi-app
    env: docker
    repo: https://github.com/pavelkortp/swapi # Change this
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: swapi-db
          property: connectionString

  # The PostgreSQL Database
  - type: psql
    name: swapi-db
    databaseName: swapi
    plan: free