name: Continuous Integration

# This workflow runs on pushes to any branch and on pull requests to the main branch
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  # The "build" job
  build:
    # Runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    strategy:
      # Defines a matrix of Node.js versions to test against
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the specified version of Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Use npm's cache to speed up dependency installation
          cache: 'npm'

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the project (compiles TypeScript to JavaScript)
      - name: Build
        run: npm run build

      # Step 5: Run the linter to check for code style issues
      - name: Lint
        run: npm run lint

      # Step 6: Run the test suite
      - name: Test
        run: npm run test
